### ISSUE TITLE
Error during first run: "enableSocialSignIn is not defined"

### ISSUE THREAD

**Issue by joaomapi** [sonalake/generator-jhipster-multitenancy#34] opened 2018-07-02 10:17 UTC
I've installed Jhipster from scratch (v5.0.1) generated an app with all values set to default.
Installed this generator (v0.9.6) and try to ran it with all defaults as well.
It fails with the following error:
`Welcome to the JHipster Multitenancy Generator v0.9.6

? What is the alias given tenants in your application? Company
events.js:167
      throw er; // Unhandled 'error' event
      ^

ReferenceError: /home/joao/.config/yarn/global/node_modules/generator-jhipster-multitenancy/generators/app/templates/src/main/java/package/domain/_User.java:169
    167| private String id;<% } %>
    168| 
 >> 169| <%_ let columnMax = 50;
    170|     if (enableSocialSignIn) {
    171|     columnMax = 100;
    172|     } _%>

enableSocialSignIn is not defined
    at eval (eval at compile (/home/joao/.config/yarn/global/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:155:5)
    at returnedFn (/home/joao/.config/yarn/global/node_modules/ejs/lib/ejs.js:653:17)
    at Object.exports.render (/home/joao/.config/yarn/global/node_modules/ejs/lib/ejs.js:416:37)
    at process (/home/joao/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:12:18)
    at applyProcessingFunc (/home/joao/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/home/joao/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy.js:63:16)
    at files.forEach.file (/home/joao/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy.js:50:10)
    at Array.forEach (<anonymous>)
    at EditionInterface.exports.copy (/home/joao/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy.js:49:9)
    at EditionInterface.module.exports [as copyTpl] (/home/joao/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
Emitted 'error' event at:
    at Immediate.setImmediate (/home/joao/.config/yarn/global/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:406:18)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
`

**Comment by joaomapi** [comment] 2018-07-02 10:29
After adding the key in the .yo-rc.json file the error changes to:

> ERROR! Copying template src/main/webapp/app/admin/user-management/_user-management.component.html.ejs failed. [Error: ENOENT: no such file or directory, open '/home/joao/.config/yarn/global/node_modules/generator-jhipster-multitenancy/generators/app/templates/src/main/webapp/app/admin/user-management/_user-management.component.html.ejs']

The file extension 'ejs' is the issue. The html file is there the ejs is not

**Comment by ivan86to** [comment] 2018-07-12 09:14
News? I have the same problem.

**Comment by joaomapi** [comment] 2018-07-12 09:23
Not that I know of. Maybe I'm doing something wrong, regardless this generator doesn't work for me.

**Comment by ciarant** [comment] 2018-07-12 09:24
Hmm. Let me have a look.

**Comment by ivan86to** [comment] 2018-07-12 09:29
I have found enableSocialSignIn not defined in _User.java , _UserDTO.java and _UserService.java 
i set enableSocialSignIn = false for now

**Comment by ciarant** [comment] 2018-07-12 09:38
Thanks. The problem is that the mechanism we use to identify exactly where to add multitenancy code to the JHipster generated classes is quite brittle. Every new JHipster release usually results in the multitenancy plugin breaking. Need to find a better way - all ideas welcome. In the meantime we'll get working on a fix.

**Comment by tcbuzor** [comment] 2018-07-17 13:52
Any progress towards a fix for this issue? I have the same problem with JHipster 5.1.0.

**Comment by jduggan83** [comment] 2018-07-17 16:49
We are currently working on a fix for the latest version, hope to have an update published in a few days.

**Comment by tcbuzor** [comment] 2018-07-17 22:36
Thanks for the update. Can you describe the approach adopted for implementing multi-tenancy in JHipster ? multiple database or multiple schema or Discriminator Strategy. I don't have a sample code but looking at the generator code it appears its the Discriminator Strategy. If so, will multiple schemas work?

**Closed** 2018-08-08 09:40 UTC

**Comment by alexander-ozkan** [comment] 2018-08-08 10:12
@tcbuzor We have just released v1.0.0 of our module. This issue has been fixed for the latest version of JHipster -v5.1.0.

**Comment by tcbuzor** [comment] 2018-08-08 23:26
Hi, I have the same issue after running: 
yarn global upgrade generator-jhipster-multitenancy && yo jhipster-multitenancy

Error:
Welcome to the JHipster Multitenancy Generator v0.9.6

? What is the alias given tenants in your application? Tenant
events.js:183
      throw er; // Unhandled 'error' event
      ^

ReferenceError: /usr/local/lib/node_modules/generator-jhipster-multitenancy/generators/app/templates/src/main/java/package/domain/_User.java:169
    167| private String id;<% } %>
    168|
 >> 169| <%_ let columnMax = 50;
    170|     if (enableSocialSignIn) {
    171|     columnMax = 100;
    172|     } _%>

enableSocialSignIn is not defined
    at eval (eval at compile (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:155:5)
    at returnedFn (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/ejs/lib/ejs.js:653:17)
    at Object.exports.render (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/ejs/lib/ejs.js:416:37)
    at process (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:12:18)
    at applyProcessingFunc (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy.js:63:16)
    at files.forEach.file (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy.js:50:10)
    at Array.forEach (<anonymous>)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy.js:49:9)
    at EditionInterface.module.exports [as copyTpl] (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
